### ISSUE TITLE
TypeError: uasort(): Argument #1 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by mprins** [turnermm/quickstats#33]
On php 8.0.13 with DW "igor" / `master`
```
TypeError: uasort(): Argument #1 ($array) must be of type array, null given
/data/www/wild-water.nl/www/dokuwiki/lib/plugins/quickstats/syntax.php(242)
#0 /data/www/wild-water.nl/www/dokuwiki/lib/plugins/quickstats/syntax.php(242): uasort()
#1 /data/www/wild-water.nl/www/dokuwiki/lib/plugins/quickstats/syntax.php(448): syntax_plugin_quickstats->sort()
#2 /data/www/wild-water.nl/www/dokuwiki/lib/plugins/quickstats/syntax.php(212): syntax_plugin_quickstats->misc_data_xhtml()
#3 /data/www/wild-water.nl/www/dokuwiki/inc/parser/renderer.php(117): syntax_plugin_quickstats->render()
#4 /data/www/wild-water.nl/www/dokuwiki/inc/parserutils.php(675): Doku_Renderer->plugin()
#5 /data/www/wild-water.nl/www/dokuwiki/inc/parserutils.php(142): p_render()
#6 /data/www/wild-water.nl/www/dokuwiki/inc/parserutils.php(89): p_cached_output()
#7 /data/www/wild-water.nl/www/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml()
#8 /data/www/wild-water.nl/www/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
#9 /data/www/wild-water.nl/www/dokuwiki/inc/template.php(99): dokuwiki\Action\Show->tplContent()
#10 [internal function]: tpl_content_core()
#11 /data/www/wild-water.nl/www/dokuwiki/inc/Extension/Event.php(133): call_user_func_array()
#12 /data/www/wild-water.nl/www/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
#13 /data/www/wild-water.nl/www/dokuwiki/inc/template.php(84): dokuwiki\Extension\Event::createAndTrigger()
#14 /data/www/wild-water.nl/www/dokuwiki/lib/tpl/wildwater/main.php(146): tpl_content()
#15 /data/www/wild-water.nl/www/dokuwiki/inc/actions.php(27): include('...')
#16 /data/www/wild-water.nl/www/dokuwiki/doku.php(122): act_dispatch()
#17 {main}
```

**Comment by turnermm** [comment]
should be fixe

**Comment by mprins** [comment]
thanks
